# Generated by Django 3.1.2 on 2021-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaires',
            old_name='comment_grade',
            new_name='comment_rating',
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de parution'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_title',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nom de la voie'),
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='comment_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de parution'),
        ),
    ]
